### ISSUE TITLE
i18n issues - not all UI strings can be translated

### ISSUE THREAD

**Issue by dikonov** [M4rtinK/modrana#253]
This is a report of existing issues that impair localization or make the translated UI look weird. They apply to many languages, especially ones with longer words.
Tested on a Jolla C.

**Strings that are not localazed**
1. "enter your search query"    prompt in search pages
2. Navigation prompts "Turn left onto" during navigation May come from OSM scout backend or Valhalla 
3. Categories of tracklogs "logs","examples","misc","online"
4. "Navigation" - Page title in the settings
5. "Network" - Page title in the settings

**Visual glitches:**
1. "unknown"  speed info page - font too large. The word "unknown" should use a smaller font. 
2. "Do you like Modrana?  Donate"   About screen - too big to fit one line. Needs a line break before "Donate". Smaller font size for lines with URLs would improve the layout of the about screen. 
3. "Cancel"   button shown during the search - button is too narrow to fit the word
4. "End"      button in the navigation mode - button is too narrow, Russian word is longer and adjusted font is much smaller than "Start"
5. "Navigate"      button in the navigation mode - button is too narrow, Russian word is longer and adjusted font is much smaller than "Start"

**Comment by M4rtinK** [comment]
Thanks for the report! I'll try to get over all the points in the next a few days. :)

**Comment by M4rtinK** [comment]
So I've looked at the not-localized-strings section first.

> Strings that are not localizable
> 
>     "enter your search query" prompt in search pages
Should be fixed now (incorrect localization function name was used).

>     Navigation prompts "Turn left onto" and other during navigation.
>     May come from OSM scout backend or Valhalla. I need a hint where to find them and whom to contact.
This seems to be because modRana is not yet passing a language hint to OSM Scout Server,
so it's returning instructions in English. I've opened issue #257 to track progress on fixing this.


>     Categories of tracklogs "logs","examples","misc","online"
The categories are actually taken from the three default folder names used to store the tracklogs (there are three folder named `logs`, `examples` and `misc`). But as this is not the first time I have seen this mentioned, some sort of alias might be needed.
Eq. if one of the well known folders is found a translatable category name will be used and while a custom folder name would be found (users can create arbitrary subfolders in the `tracklogs` folder) the folder name would be used as category name.

>     "Navigation" - Page title in the settings
>     "Network" - Page title in the settings
Both section names should now be translatable (were not marked for translation by mistake).
>     "km/h", "m/h" - speed values in the Info screens
This should be now translatable as well.

I'll take a look at the visual glitches next.

**Comment by dikonov** [comment]
I have updated the strings in transifex.

**Comment by M4rtinK** [comment]
> I have updated the strings in transifex.

Thanks! I've pulled in the latest translations and did a new build (0.55.14):
http://repo.merproject.org/obs/home:/MartinK:/sailfish:/modrana/sailfish_latest_armv7hl/noarch/
Let me know if all looks fine now translation wise. :)

**Comment by dikonov** [comment]
I found that "A point on the map" and "An arbitrary point on the map" strings in POI properties page are still not translatable. The "distance:" label in the same page has spurious </b> tag appended. 
Other non translatable strings:
"2D fix"/"3D fix" in the GPS info page.
"Show on map" in POI properties page (menu item)

Possible beautifications:

The start, finish, navigate and clear (route) buttons in the main map screen use very different font sizes to squeeze in words that have different length in Russian. It would look better if the button width would change instead of the font size.

"tracklogs" in the Track logs list page are always plural. Properly translated strings for "1, (0 and 2-4), 5+  tracklogs" have different case endings and .ts files have support for such variation, which is apparently not used.

**Comment by M4rtinK** [comment]
> I found that "A point on the map" and "An arbitrary point on the map" strings in POI properties page are still not translatable.
Those should be all fixed now.

> The "distance:" label in the same page has spurious </b> tag appended.
That's weird - so I've just split the markup from the translatable "distance" string.

> Other non translatable strings: "2D fix"/"3D fix" in the GPS info page. "Show on map" in POI properties page (menu item) 
Should be now fixed as well. :)

>Possible beautifications: The start, finish, navigate and clear (route) buttons in the main map screen use very different font sizes to squeeze in words that have different length in Russian. It would look better if the button width would change instead of the font size. 
Lets say that it was "an interesting experience" but all on map buttons should now grow based on text length & their height should now always depend on a fraction of the screen size. So not only should translations look better on these buttons but more screen size rations should now work as well. :)

>"tracklogs" in the Track logs list page are always plural. Properly translated strings for "1, (0 and 2-4), 5+  tracklogs" have different case endings and .ts files have support for such variation, which is apparently not used.
So I've just added a function that assembles an appropriate string based on the number of tracklogs in the given category.

I've release a new modRana versions with the fixes (0.55.15), you can give it another spin (the repo folder URL remains the same). :)

**Comment by dikonov** [comment]
I fixed the new strings in transifex. 

The /usr/share/harbour-modrana/translation folder looks strange. It contains both source .po / .ts files and their compiled versiond .mo / .qm. Normally only .mo and .qm files are found in the localization folder and no subfolders are used there. I manually updated the ru_RU.qm to test the new strings, but it did not change the UI. Maybe the strings are still embedded (or some very weird caching exists in qml).  

The routing buttons do look nicer! Thanks for the update!

* By the way, the 0.55.15 rpm could initially be run only from treminal. Starting from the launcher shortcut after rpm -e and installation of the new package failed for some reason. It works normally after a reboot.

**Comment by M4rtinK** [comment]
> I fixed the new strings in transifex.
> 
> The /usr/share/harbour-modrana/translation folder looks strange. It contains both source .po / .ts files and their compiled versiond .mo / .qm. Normally only .mo and .qm files are found in the localization folder and no subfolders are used there.

Yeah, the .po & .ts files are definitely not need to be installed and I'll try to get rid of them. IIRC subfolders are somehow needed for the translations of the Python part, even though that seems to not be very needed yet, with majority of translations happening in the QML part of modRana.


>I manually updated the ru_RU.qm to test the new strings, but it did not change the UI. Maybe the strings are still embedded (or some very weird caching exists in qml).  

Yeah, it's weird - there should be just that one qm file, even according to RPM:

```
# rpm -ql harbour-modrana | grep ru_RU.qm
/usr/share/harbour-modrana/translations/harbour-modrana-ru_RU.qm
```

So if you are still getting the old Russian translations even after you have replaced that file then I have no idea where that is coming from. Maybe try to reboot, in case some runtime caches are being used ? In any case quite a big & annoying mystery.

> 
> The routing buttons do look nicer! Thanks for the update!

Cool! :)
> 
> * By the way, the 0.55.15 rpm could initially be run only from treminal. Starting from the launcher shortcut after rpm -e and installation of the new package failed for some reason. It works normally after a reboot.

Weird - seem to be fine for me (I've installed it with `zypper install http://repo.merproject.org/obs/home:/MartinK:/sailfish:/modrana/sailfish_latest_armv7hl/noarch/harbour-modrana-0.55.15-1.1.noarch.rpm` ).

> "to true north" string in Location info page lost translatability in 0.55.15 and is shown in English. It is available and translated in transifex. A typo somewhere?

That's strange - it is marked for translation in the code:
https://github.com/M4rtinK/modrana/blob/master/modules/gui_modules/gui_qt5/qml/InfoLocationPage.qml#L83

And I don't think I have touched it recently.

**Comment by M4rtinK** [comment]
So I've handled some more of your suggestions:
- the donate text on the About page should now wrap
- the cancel button should now resize based on text length
- the unknown string is now half the font size of regular speed string
- only compiled translation files should be now shipped (this apparently reduced installed size by ~900 kB)

All of this should be in 0.55.17 I've just built on OBS. :)

**Comment by dikonov** [comment]
Running Modrana 0.55.19 now. The fixes are there now, but the new  Map/Сlear menu is English only (already translated in transifex). Besides the big main menu icon buttons got shifted down, which sets their captions partly offscreen. See screenshots.

![](mtp://%5Busb%3A001,015%5D/Mass%20storage/Pictures/Screenshots/Screenshot-18-06-28-11-32-52.png)

**Comment by dikonov** [comment]
Some translations from Transifex e.g. "Delete this POI ?" are not commited to the git.
